myblog/blog/urls.py
from django.conf.urls import url, include
from django.views.generic import RedirectView

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$',
        views.IndexView.as_view(), name='index'),
    url(r'^article/(?P<title>\w+)/$',
        views.DetailView.as_view(), name='detail_post'),
    url(r'^article/new$',
        views.NewArticle.as_view(), name='new_post'),
    url(r'^article/(?P<title>\w+)/edit$',
        views.UpdateArticle.as_view(), name='edit_post'),
    url(r'^article/(?P<title>\w+)/delete',
        views.DeleteArticle.as_view(), name='delete_post'),
    url('^markdown/', include('django_markdown.urls')),
    url(r'^login/$',
        views.Login.as_view(), name='login'),
    url(r'^register/$',
        views.Register.as_view(), name='register'),
    url(r'^logout/$',
        views.Logout.as_view(), name='logout'),
    url(r'^feed/$',
        views.LatestEntriesFeed()),
    url(r'^.*$',
        RedirectView.as_view(url='/')),
]

myblog/myblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

myblog/blog/models.py
import datetime

from django.core.urlresolvers import reverse
from django.db import models
from django_markdown.models import MarkdownField


class BlogPost(models.Model):
    title = models.CharField(max_length=200, unique=True)
    body = MarkdownField()
    timestamp = models.DateTimeField(default=datetime.datetime.now)

    def get_absolute_url(self):
        return reverse('blog:detail_post', args=[self.title])

    def __str__(self):
        return self.title

myblog/blog/forms.py
from django import forms

from django_markdown.widgets import MarkdownWidget

from .models import BlogPost


class PostForm(forms.ModelForm):
    title = forms.CharField(label='标题',
                            max_length=200)
    body = forms.CharField(label='正文',
                           widget=MarkdownWidget)

    class Meta:
        model = BlogPost
        fields = ('title', 'body')

myblog/blog/views.py
from django.contrib.auth import login as login_user
from django.contrib.auth import logout as logout_user
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
# from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.syndication.views import Feed
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import View
from django.views import generic

from .forms import PostForm
from .models import BlogPost


class IndexView(generic.ListView):
    model = BlogPost
    template_name = 'index.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return BlogPost.objects.order_by('-timestamp')


class DetailView(generic.DetailView):
    model = BlogPost
    template_name = 'post/detail.html'
    context_object_name = 'post'
    slug_field = 'title'
    slug_url_kwarg = 'title'

    # def get_object(self, **kwargs):
        # title = self.kwargs.get('title')
        # try:
            # article = BlogPost.objects.get(title=title)
        # except BlogPost.DoesNotExist:
            # raise Http404('Article does not exist')
        # return article


class MyLoginMixin(LoginRequiredMixin):
    login_url = '/login'
    # redirect_field_name = 'redirect_to'


# class NewArticle(MyLoginMixin, FormView):
    # template_name = 'post/new.html'
    # form_class = PostForm
    # success_url = '/'


class NewArticle(MyLoginMixin, CreateView):
    model = BlogPost
    # fields = ['title', 'body']
    form_class = PostForm
    template_name = 'post/new.html'


class UpdateArticle(MyLoginMixin, UpdateView):
    model = BlogPost
    # fields = ['title', 'body']
    form_class = PostForm
    template_name = 'post/edit.html'

    def get_object(self):
        return BlogPost.objects.get(title=self.kwargs.get('title'))


# @login_required
# def new_article(request):
    # if request.method == 'POST':
        # form = PostForm(request.POST)
        # if form.is_valid():
            # form.save()
            # return redirect('/')
        # print(form)
        # return redirect(reverse('blog:new_post'))
    # else:
        # form = PostForm()
        # return render(request, 'post/new.html', {'form': form})


# @login_required
# def edit_article(request, title):
    # pass


class DeleteArticle(MyLoginMixin, View):
    def get(self, request, title):
        post = BlogPost.objects.filter(title=title)
        post.delete()
        return redirect('/')


class Login(View):
    def get(self, request):
        form = AuthenticationForm()
        request.session['login_from'] = request.META.get('HTTP_REFERER', '/')
        return render(request, 'login.html', {'form': form})

    def post(self, request):
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            login_user(request, form.get_user())
            return HttpResponseRedirect(request.session.get('login_from', '/'))
        return redirect(reverse('blog:index'))  # Need to be corrected


class Register(View):
    def get(self, request):
        form = UserCreationForm()
        return render(request, 'register.html', {'form': form})

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            login_user(request)
        return redirect(reverse('blog:index'))


class Logout(View):
    def get(self, request):
        logout_user(request)
        return redirect('/')


class LatestEntriesFeed(Feed):
    title = 'Feeds'
    link = '/feed/'
    description = 'Show lastest posts'

    def items(self):
        return BlogPost.objects.order_by('-timestamp')[:5]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.body

    def item_link(self, item):
        return reverse('blog:detail_post', args=[item.title])

myblog/blog/templates/base.html
<html>
    <head>
        <style type="text/css">
            body{color:#efd;background:#453;padding:0 5em;margin:0}
            h1{padding:2em 1em;background:#675;text-align: center}
            h2{color:#bf8;border-top:1px dotted #fff;margin-top:2em}
            p{margin:1em 0}
        </style>
    </head>

    <body>
        {% if user.is_authenticated %}
        <strong>欢迎{{ user }}</strong>
        <a href="{% url 'blog:logout' %}">登出</a>
        {% else %}
        <a href="{% url 'blog:register' %}">注册</a>
        <a href="{% url 'blog:login' %}">登录</a>
        {% endif %}
        <h1>写一个blog-阿楠你学会了嘛</h1>
        {% block content %}
        {% endblock %}
    </body>
</html>

myblog/blog/templates/index.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated %}
    <a href="{% url 'blog:new_post' %}">写文章</a>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{% url 'blog:detail_post' post.title %}">{{ post.title }}</a>
        </h2>
        <p>{{ post.timestamp }}</p>
        <p>{{ post.body }}</p>
    {% endfor%}
{% endblock %}

myblog/blog/templates/login.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="Login">
</form>
{% endblock %}

myblog/blog/templates/post/detail.html
{% extends "base.html" %}

{% block content %}
    {% if user.is_authenticated %}
    <a href="{% url 'blog:edit_post' post.title %}">编辑文章</a>
    <a href="{% url 'blog:delete_post' post.title %}">删除文章</a>
    {% endif %}
    <a href="/">回到主页</a>
    <h2>{{ post.title }}</h2>
    <p>{{ post.timestamp }}</p>
    <p>{{ post.body }}</p>

<!-- 多说评论框 start -->
<div class="ds-thread" data-thread-key="{{ post.id }}" data-title="{{ post.title }}" data-url="{% url 'blog:detail_post' post.title %}"></div>
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"halfcrazy"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0] 
		 || document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- 多说公共JS代码 end -->
{% endblock %}

myblog/blog/templates/post/edit.html
{% extends "base.html" %}

{% block content %}
<a href="/">回到主页</a>
{% if form.errors %}
    <p style="color: red;">
        {# pulralize 是filter，用来判断是否为添加's'来表示单词的复数形式#}
        Please correct the error{{ form.errors|pluralize }} below.
    </p>
{% endif %}
<form action="" method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="更新">
</form>
{% endblock %}

myblog/blog/templates/post/new.html
{% extends "base.html" %}

{% block content %}
<a href="/">回到主页</a>
{% if form.errors %}
    <p style="color: red;">
        {# pulralize 是filter，用来判断是否为添加's'来表示单词的复数形式#}
        Please correct the error{{ form.errors|pluralize }} below.
    </p>
{% endif %}
<form action="" method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="创建">
</form>
{% endblock %}

myblog/blog/templates/register.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
   {% csrf_token %}
   {{ form.as_p }}
   <input type="submit" value="Register">
</form>
{% endblock %}